services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: R3s3rv#313
        MONGO_INITDB_DATABASE: master  # Specifies the initial database
      volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      ports:
        - "27017:27017"  # Exposing the MongoDB port

  memcached:
      image: memcached:latest
      container_name: memcached
      ports:
        - "11211:11211"
  dataloader:
    image: ghcr.io/19btech/fyntrac/docker/dataloader:latest  # Removed the extra ':latest'
    container_name: fyntrac-dataloader
    working_dir: /dataloader  # Set the working directory in the container
    ports:
    - "8089:8089"  # Map the port (adjust as needed)
    entrypoint: ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.reserv.dataloader.DataloaderApplication"]  # Command to run the jar file
    environment:
    - SPRING_PROFILES_ACTIVE=test  # Set the active Spring profile
    depends_on:
    - mongodb
    - memcached
  model:
    image: ghcr.io/19btech/fyntrac/docker/model:latest  # Removed the extra ':latest'
    container_name: fyntrac-model
    working_dir: /model  # Set the working directory in the container
    ports:
      - "8089:8089"  # Map the port (adjust as needed)
    entrypoint: [ "java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.fyntrac.model.ModelApplication" ]  # Command to run the jar file
    environment:
      - SPRING_PROFILES_ACTIVE=test  # Set the active Spring profile
    depends_on:
      - dataloader
  gl:
    image: ghcr.io/19btech/fyntrac/docker/gl:latest  # Removed the extra ':latest'
    container_name: fyntrac-gl
    working_dir: /model  # Set the working directory in the container
    ports:
      - "8089:8089"  # Map the port (adjust as needed)
    entrypoint: [ "java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.fyntrac.gl.GlApplication" ]  # Command to run the jar file
    environment:
      - SPRING_PROFILES_ACTIVE=test  # Set the active Spring profile
    depends_on:
      - model
  reporting:
    image: ghcr.io/19btech/fyntrac/docker/reporting:latest  # Removed the extra ':latest'
    container_name: fyntrac-reporting
    working_dir: /model  # Set the working directory in the container
    ports:
      - "8089:8089"  # Map the port (adjust as needed)
    entrypoint: [ "java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.fyntrac.reporting.ReportingApplication" ]  # Command to run the jar file
    environment:
      - SPRING_PROFILES_ACTIVE=test  # Set the active Spring profile
    depends_on:
      - gl