services:
  postgres:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: fyntrac-postgres  # Name of the container
    environment:
      POSTGRES_USER: root  # Set the PostgreSQL user
      POSTGRES_PASSWORD: R3s3rv#313  # Set the PostgreSQL password
      POSTGRES_DB: fyntrac  # Set the default database to create
    ports:
      - "5432:5432"  # Map port 5432 of the container to port 5432 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in a named volume

volumes:
  postgres_data:  # Define a named volume for data persistence