spring.application.name=reporting
server.port=8084
spring.profiles.active=dev

# OAuth2 Resource Server - JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://fyntrac-auth-q8clqw.us1.zitadel.cloud
# The dataloader will now accept tokens where the audience is either its own Client ID OR the Project ID
spring.security.oauth2.resourceserver.jwt.audiences=361565151243074064

